# here we will be understanding expression context object 
# now what it is context object -> its a object that gives you meta data about all the things happening in github 
# now why it is needed -> working with env variables can require expression to call variables also context object is something used in industry to push data to db
## to track data and every job 

name: My context
on: issues # tells to run this manually when some one runs it on github 
jobs:
  context-info:
    runs-on: ubuntu-latest
    steps:
      - name: Get issue events
        run: |
         curl -s \
           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
           -H "Accept: application/vnd.github+json" \
           "${{ github.event.issue.events_url }}" | jq .