name: Test Workflow # name of workflow 
on: [push,workflow_dispatch] # trigger actions/events -> can run as many as you want 
jobs:
  tester:
    runs-on: ubuntu-latest # spin up ubuntu container in a axure server 
    steps:
      - name: Pushing Code to Container 
        uses: actions/checkout@v7 # actions are 3rd party tools / application developed by devdelopers use to perform repeated tasks 
      - name: Installing NodeJS 
        uses: actions/setup-node@v6 
        with: 
          node-version: 25 # to add up configuration with actions 
      - name: Installing Dependencies 
        run: npm install 
      - name: Run Unit Tests 
        run: npm run test
  builder:
     needs: tester
     runs-on: ubuntu-latest # spin up ubuntu container in a axure server 
     steps:
      - name: Pushing Code to Container 
        uses: actions/checkout@v7 # actions are 3rd party tools / application developed by devdelopers use to perform repeated tasks 
      - name: Installing NodeJS 
        uses: actions/setup-node@v6 
        with: 
          node-version: 25 # to add up configuration with actions 
      - name: Installing Dependencies 
        run: npm install  
      - name: Building your code 
        run: npm run build 
      - name: upload build project
        uses: actions/upload-artifact@v7 # uploadind data generated after the job artifact/asset 
        with:
          name: artifacts-list
          path: |
            dist 
            package.json 
  deployer:
      needs: builder
      runs-on: ubuntu-latest
      steps:
        - name: Deploying your code
          run: echo we are deploying it
    