name: Test Workflow # name of workflow 
on: [push,workflow_dispatch] # trigger actions/events -> can run as many as you want 
jobs:
  tester:
    runs-on: ubuntu-latest # spin up ubuntu container in a axure server 
    steps:
      - name: Pushing Code to Container 
        uses: actions/checkout@v7 # actions are 3rd party tools / application developed by devdelopers use to perform repeated tasks 
      - name: Installing NodeJS 
        uses: actions/setup-node@v6 
        with: 
          node-version: 25 # to add up configuration with actions 
      - name: Installing Dependencies 
        run: npm install 
      - name: Run Unit Tests 
        run: npm run test
  builder:
     needs: tester
     runs-on: ubuntu-latest # spin up ubuntu container in a axure server 
     outputs:
        output-value: ${{ steps.refer-id.outputs.key }} # this will refernce to value generated in that step 
     steps:
      - name: Pushing Code to Container 
        uses: actions/checkout@v7 # actions are 3rd party tools / application developed by devdelopers use to perform repeated tasks 
      - name: Installing NodeJS 
        uses: actions/setup-node@v6 
        with: 
          node-version: 25 # to add up configuration with actions 
      - name: Installing Dependencies 
        run: npm install  
      - name: Building your code 
        run: npm run build 
      - name: upload build project
        uses: actions/upload-artifact@v7 # uploadind data files generated after the job artifact/asset 
        with:
          name: artifacts-list
          path: |
            dist 
            package.json 
      - name: uploading value to output 
        id: refer-id # this id will be unique to step and will be use for refer my output 
        run: echo 'key=hello_world' >> $GITHUB_OUTPUT  # now i have uploaded a key value to a pointer pointing to internal github files consist key value  
      # run: echo ::set-output name=key::value        # now this is another way writng it to a $GITHUB_OUTPUT  pointer 
  deployer:
      needs: builder
      runs-on: ubuntu-latest
      steps:
        - name: Download artifacts 
          uses: actions/download-artifact@v8
          with:
            name: artifacts-list # there could be many artifacts 
        - name: Show Path # just to make sure all artifacts should be at exact loactions
          run: ls 
        - name: Show output
          run: echo ${{ needs.builder.outputs.output-value}} # taking output in another job 
        - name: Deploying your code
          run: echo we are deploying it

    